[[manager.prepend_keymap]]
on = ["L"]
run = "open --interactive"
desc = "Open the selected files interactively"

[[manager.prepend_keymap]]
on = ["S"]
run = "shell zsh --block --confirm"
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["R"]
run = 'search rg'
desc = "Search files by content using ripgrep"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = ["q"]
run = "close"
desc = "Close the current tab, or quit if it is last tab"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["k"]
run = "plugin --sync arrow --args=-1"

[[manager.prepend_keymap]]
on = ["j"]
run = "plugin --sync arrow --args=1"

[[tasks.prepend_keymap]]
on = [ "q" ]
run = "close"
desc = "Hide the task manager"

